version: '3.8'

services:
    psql-db:
        image: postgres
        container_name: psql-db
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=client
        ports:
            - '5433:5432'

    client:
        container_name: client_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8081:8083'
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/client
            - SPRING_DATASOURCE_USERNAME=admin
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        depends_on:
            - psql-db
