openapi: 3.0.1
info:
  title: Customer API
  description: API pour gérer les clients
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /internal/api/v1/customers/getAll:
    get:
      tags:
        - "customers"
      operationId: "getAllCustomers"
      summary: Récupérer tous les clients
      responses:
        '200':
          description: Succès. Renvoie la liste de tous les clients.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      required:
        - createdAt
        - name
        - username
        - firstName
        - lastName
        - postalCode
        - city
        - profileFirstName
        - profileLastName
        - companyName
      properties:
        createdAt:
          type: string
          format: date-time
          example: "2023-08-29T16:28:58.454Z"
        name:
          type: string
          example: "Jan Schiller"
        username:
          type: string
          example: "Kailee.Greenholt73"
        firstName:
          type: string
          example: "Keven"
        lastName:
          type: string
          example: "Kris"
        postalCode:
          type: string
          example: "61432-1180"
        city:
          type: string
          example: "St. Joseph"
        profileFirstName:
          type: string
          example: "Mitchell"
        profileLastName:
          type: string
          example: "Carter"
        companyName:
          type: string
          example: "Bechtelar LLC"