openapi: 3.0.1
info:
  title: Customer API
  description: API pour gérer les clients
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:

  /internal/api/v1/customers:
    get:
      tags:
        - "customers"
      operationId: "getAllCustomers"
      summary: Récupérer tous les clients
      responses:
        '200':
          description: Succès. Renvoie la liste de tous les clients.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: Mauvaise requête
        '404':
          description: Clients non retrouvables
        '500':
          description: Erreur interne du serveur

    post:
      tags:
        - "customers"
      operationId: "createCustomer"
      summary: Ajoute un nouveau client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'

      responses:
        '201':
          description: Client ajouté avec succès
        '400':
          description: Mauvaise requête.
        '500':
          description: Erreur interne du serveur

  /internal/api/v1/customers/{id}:
    get:
      tags:
        - "customers"
      operationId: "getCustomerById"
      parameters:
        - name: id
          in: path
          description: ID du client à retrouver
          required: true
          schema:
            type: integer
            format: int64
      summary: Récupérer un client à partir de son identifiant
      responses:
        '200':
          description: Succès. Renvoie le client ayant l'identifiant concerné.
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: ID invalide
        '404':
          description: Client non retrouvable

    put:
      tags:
        - "customers"
      operationId: "updateCustomer"
      summary: Modifie un clie nt
      parameters:
        - name: id
          in: path
          description: ID du client à retrouver
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Client modifié avec succès
        '400':
          description: Mauvaise requête.
        '500':
          description: Erreur interne du serveur

    delete:
      tags:
        - "customers"
      operationId: "deleteCustomerById"
      parameters:
        - name: id
          in: path
          description: ID du client à supprimer
          required: true
          schema:
            type: integer
            format: int64
      summary: Supprimer un client à partir de son identifiant
      responses:
        '400':
          description: ID invalide

components:
  schemas:
    Customer:
      type: object
      required:
        - name
        - username
        - firstName
        - lastName
        - postalCode
        - city
        - profileFirstName
        - profileLastName
        - companyName
      properties:
        name:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        postalCode:
          type: string
        city:
          type: string
        profileFirstName:
          type: string
        profileLastName:
          type: string
        companyName:
          type: string