on:
  pull_request:
    branches: [ develop, release ]

jobs:
  #Used to check files structure and prevent useless push
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'
          architecture: x64

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Verify Ignored Directories
        run: |
          forbidden_dirs="./.idea ./target ./node_modules ./.vscode"
          for dir in $forbidden_dirs; do
            if [[ -d "$dir" ]]; then
              echo "Forbidden directory '$dir' found. Please ensure it's ignored in .gitignore."
              exit 2
            fi
          done

      - name:
          Maven with Checkstyle
        uses: maven-central/maven-action@v2
        with:
          maven-version: '3.8.6'  # Update as needed

      - name:
          CheckStyle
        run: |
          mvn clean verify checkstyle:check  

      - name: Upload Code Quality Reports (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: target/checkstyle-reports/*.xml

