on:
  pull_request:
    branches:
      - develop
      - release
jobs:

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn checkstyle:check

      - name: Verify Ignored Directories
        run: |
          forbidden_dirs="./.idea ./target ./node_modules ./.vscode"
          for dir in $forbidden_dirs; do
            if [[ -d "$dir" ]]; then
              echo "Forbidden directory '$dir' found. Please ensure it's ignored in .gitignore."
              exit 2
            fi
          done
