on:
  pull_request:
    branches: [ develop, release ]

jobs:
  java-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages (optional)
        uses: actions/cache@v3  # Cache Maven dependencies (optional)
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and test Java code (using Maven)
        run: mvn clean verify  # Clean, build, and run tests

      - name: Run Checkstyle (optional)
        uses: dbelyaev/action-checkstyle@master  # Check code style (optional)
        with:
          java-version: 17
          distribution: 'temurin'
          architecture: x64
          github_token: ${{ secrets.github_token }}
          checkstyle_config: sun_checks.xml
          reporter: github-pr-review  # Report findings in PR comments

      - name: Verify Ignored Directories
        run: |
          forbidden_dirs="./.idea ./target ./node_modules ./.vscode"
          for dir in $forbidden_dirs; do
            if [[ -d "$dir" ]]; then
              echo "Forbidden directory '$dir' found. Please ensure it's ignored in .gitignore."
              exit 2
            fi
          done
