name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests with Maven
        run: mvn clean test

      - name: List files after tests
        run: ls -R target

      - name: Generate Jacoco coverage report
        run: mvn jacoco:report

      - name: List files after Jacoco report
        run: ls -R target/site/jacoco

      - name: Archive Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  add-coverage-to-pr:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Jacoco report
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
