on:
  pull_request:
    branches:
      - develop
      - release

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and test with Maven
        run: mvn test

  jacoco:
    runs-on: ubuntu-latest
    needs: [tests] # Ensure that the tests job has completed successfully before running this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Generate Jacoco report
        run: mvn jacoco:report

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/coverage
