name: Integration workflow

on:
  pull_request:
    branches: [develop]
  push:
    branches:
      - release
      - develop

jobs:

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Execute Checkstyle
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

  jacoco:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test with Maven
      run: mvn clean verify jacoco:report

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
          name: report.xml
          path:
            ${{ github.workspace }}/target/jacoco-report/jacoco.xml


    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths:
          ${{ github.workspace }}/target/jacoco-report/*.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 95
        min-coverage-changed-files: 10
        title: '# :lobster: Coverage Report'
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'
        continue-on-error: false
      
    - name: Get the Coverage info
      run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage test"

          - name: Create Coverage Comment
          run: |
            overall_coverage=${{ steps.jacoco.outputs.coverage-overall }}
            changed_files_coverage=${{ steps.jacoco.outputs.coverage-changed-files }}
            if [ -z "$changed_files_coverage" ]; then
              changed_files_coverage="There is no coverage information present for the Files changed"
            fi
    
            coverage_report="🦞 Coverage Report\n"
            coverage_report+="Overall Project\t${overall_coverage}%\t🔴\n"
            coverage_report+="${changed_files_coverage}"
    
            echo "$coverage_report"
            echo "##[set-output name=coverage-comment::$coverage_report]"
    
    - name: Post Coverage Comment to PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Coverage Report
        message: ${{ steps.coverage-info.outputs.coverage-comment }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      