on:
  pull_request:
    branches:
      - develop
      - release
jobs:

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

      - name: Build and test with Maven
        run: mvn test


      - name: Verify Ignored Directories
        run: |
            forbidden_dirs=".idea node_modules .vscode"
            missing_from_gitignore=false
            for dir in $forbidden_dirs; do
              if [[ -d "$dir" ]]; then
                if ! grep -qx "$dir" .gitignore; then
                  echo "Forbidden directory '$dir' found and is not listed in .gitignore."
                  missing_from_gitignore=true
                fi
              fi
            done  
            if $missing_from_gitignore; then
              echo "Some forbidden directories are not listed in .gitignore. Please ensure they are ignored."
              exit 2
            fi'

    
