name: Integration workflow

on:
  pull_request:
    branches: [develop]
  push:
    branches:
      - release
      - develop

jobs:

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Execute cCheckstyle
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test with Maven
      run: mvn clean verify jacoco:report

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2
      with:
          name: jacoco-report
          path: target/jacoco-report/jacoco.xml

  jacoco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/jacoco-report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 95
          min-coverage-changed-files: 0
          title: '# :lobster: Coverage Report'
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'


