name: Integration workflow

on:
  pull_request:
    branches: [develop]
  push:
    branches:
      - release
      - develop

jobs:

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

#      - name: Execute cCheckstyle
#        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
            distribution: 'corretto' # See 'Supported distributions' for available options
            java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
            coverage_results_path: 'target/site/jacoco/jacoco.xml'
            coverage_report_title: 'Test coverage results'
            coverage_report_name: 'Test coverage results'
            github_token: ${{ secrets.GITHUB_TOKEN }}




  jacoco:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build and test with Maven
      run: mvn clean verify jacoco:report

#    - name: build 2
#      run: mvn --batch-mode --update-snapshots test

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
          name: report.xml
          path:
            ${{ github.workspace }}/target/jacoco-report/jacoco.xml


            # generates coverage-report.md and publishes as checkrun
    - name: JaCoCo Code Coverage Report
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v5.0
      with:
        coverage_results_path: jacoco-report/jacoco.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: false

  # Publish Coverage Job Summary  # Optional
    - name: Add Jacocoo report to workflow run summary
      run: |
        echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
        echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
        echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
        echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

#  # uploads the coverage-report.md artifact  # Optional
#    - name: Upload Code Coverage Artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: code-coverage-report-markdown
#        path: */coverage-results.md
#        retention-days: 1

#    - name: Add coverage to PR
#      id: jacoco
#      uses: madrapps/jacoco-report@v1.6.1
#      with:
#        paths:
#          ${{ github.workspace }}/target/jacoco-report/*.xml
#        token: ${{ secrets.GITHUB_TOKEN }}
#        min-coverage-overall: 95
#        min-coverage-changed-files: 0
#        debug-mode: true
#        title: '# :lobster: Coverage Report'
#        pass-emoji: ':green_circle:'
#        fail-emoji: ':red_circle:'
#        update-comment: true
#        continue-on-error: false
#        include-code: true
#
#    - name: Get the Coverage info
#      run: |
#          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
#          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

#  jacoco:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      pull-requests: write
#    needs: [build]
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: 17
#          distribution: 'adopt'
#
#


