on:
  pull_request:
    branches:
      - develop
      - release

permissions:
  contents: read
  pull-requests: write

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and test with Maven
        run: mvn test

  jacoco:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Generate Jacoco report
        run: mvn jacoco:report

      - name: Upload Jacoco report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: '# :lobster: Coverage Report'
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
