name: CI

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Generate Jacoco coverage report
        run: mvn jacoco:report

      - name: Archive Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  checkstyle:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run Checkstyle
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyle-rules.xml

  verify-ignored-directories:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Ignored Directories
        run: |
          forbidden_dirs=".idea node_modules .vscode"
          missing_from_gitignore=false
          for dir in $forbidden_dirs; do
            if [[ -d "$dir" ]]; then
              if ! grep -qx "$dir" .gitignore; then
                echo "Forbidden directory '$dir' found and is not listed in .gitignore."
                missing_from_gitignore=true
              fi
            fi
          done  
          if $missing_from_gitignore; then
            echo "Some forbidden directories are not listed in .gitignore. Please ensure they are ignored."
            exit 2

  add-coverage-to-pr:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Jacoco report
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
