on:
  pull_request:
    branches:
      - 'develop'
      - 'release'
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml


#      - name: Verify Ignored Directories
#        run: |
#          forbidden_dirs="./.idea ./target ./node_modules ./.vscode"
#          for dir in $forbidden_dirs; do
#            if [[ -d "$dir" ]]; then
#              echo "Forbidden directory '$dir' found. Please ensure it's ignored in .gitignore."
#              exit 2
#            fi
#          done
